name: selenium_FinDateGet

on:
   schedule:
     - cron: '0 9 * * *'
     
jobs:
  build:
    runs-on: windows-2019
  steps: 
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install
      run: |
        python -m pip install --urgade pip
        pip install selenium==4.8.4
        run python ./company_repurchases.py
